version: '3.8'

services:
  myinstantsbot:
    image: heylouiz/myinstantsbot:latest
    container_name: myinstantsbot
    restart: unless-stopped
    environment:
     - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
     - MYINSTANTS_USERNAME=${MYINSTANTS_USERNAME}
     - MYINSTANTS_PASSWORD=${MYINSTANTS_PASSWORD}
    volumes:
     - .:/app
